modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="deltachunk"
version="0.1.0"
displayName="Delta Chunk"
authors="user19870"
description='''
Single-player procedural world storage using WAM files.
'''


 
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
