modLoader="javafml"
loaderVersion="[1,)"

license="MIT"

[[mods]]
modId="deltachunk"
version="0.1.0"
displayName="Delta Chunk"
authors="user19870"
description='''
Single-player procedural world storage using WAM files.
'''


 
[[dependencies.deltachunk]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.deltachunk]]
modId="minecraft"
type="required"
versionRange="[1,)"
ordering="NONE"
side="BOTH"
