package com.deltachunk;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.commands.arguments.coordinates.BlockPosArgument;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * /deltachunk add x1 y1 z1 x2 y2 z2
 * /deltachunk delete x1 y1 z1 x2 y2 z2
 *
 * Manual, in-game range tool for editing WAM data directly, without
 * needing to actually break/place every block by hand.
 *
 *   add    - snapshots the CURRENT world state (block + any block
 *            entity NBT) of every position in the box and writes it
 *            into WAM as if the player had made that change
 *            themselves. Useful for retroactively "claiming" a
 *            structure (e.g. one built by a datapack/mod, or one the
 *            player wants to guarantee survives compaction) without
 *            needing DeltaChunk to have been present when it was
 *            built.
 *   delete - removes any recorded WAM entries for every position in
 *            the box. Useful for undoing an accidental "add", or for
 *            deliberately letting a previously-claimed area go back
 *            to being regenerated by the world generator next time
 *            its chunk is stripped.
 *
 * Both operations work directly against WamStore's on-disk region
 * files (via mergeRegion / removeRegion) and do NOT touch the
 * in-memory DeltaIndex used for this-session automatic tracking --
 * they take effect immediately on disk rather than waiting for the
 * end-of-session flush, since a player explicitly running a command
 * expects it to be durable right away.
 *
 * Permission: requires permission level 2 (same as most world-editing
 * commands like /fill), since this can both duplicate build data
 * into permanent storage and cause future regeneration to silently
 * drop content over a large volume if misused.
 */
public final class DeltaCommand {

    private static final Logger LOGGER =
            LoggerFactory.getLogger(DeltaCommand.class);

    /*
     * Safety cap on how many blocks a single invocation can touch.
     * Without a cap, a careless /deltachunk add covering, say, a
     * 2000x256x2000 box would try to build tens of millions of NBT
     * entries in memory and in the command's own result message
     * calculation. 1,048,576 is 1024*1024 -- generous for legitimate
     * "claim this whole build" use (e.g. a 100x100x100 box is
     * 1,000,000 blocks and just barely fits) while still refusing
     * the truly unbounded cases.
     */
    private static final long MAX_BLOCKS_PER_INVOCATION = 1_048_576L;

    private DeltaCommand() {
    }

    public static void register(
            CommandDispatcher<CommandSourceStack> dispatcher
    ) {

        dispatcher.register(
                Commands.literal("deltachunk")
                        .requires(source -> source.hasPermission(2))
                        .then(
                                Commands.literal("add")
                                        .then(corners(DeltaCommand::runAdd))
                        )
                        .then(
                                Commands.literal("delete")
                                        .then(corners(DeltaCommand::runDelete))
                        )
        );
    }

    /**
     * Shared argument shape for both add and delete: x1 y1 z1 x2 y2
     * z2, each a block position argument (so relative "~" coordinates
     * work the same way /fill accepts them).
     */
    private static com.mojang.brigadier.builder.ArgumentBuilder<CommandSourceStack, ?> corners(
            RangeCommandExecutor executor
    ) {

        return Commands.argument("x1", IntegerArgumentType.integer())
                .then(
                        Commands.argument("y1", IntegerArgumentType.integer())
                                .then(
                                        Commands.argument("z1", IntegerArgumentType.integer())
                                                .then(
                                                        Commands.argument("x2", IntegerArgumentType.integer())
                                                                .then(
                                                                        Commands.argument("y2", IntegerArgumentType.integer())
                                                                                .then(
                                                                                        Commands.argument("z2", IntegerArgumentType.integer())
                                                                                                .executes(context ->
                                                                                                        executor.run(
                                                                                                                context,
                                                                                                                new BlockPos(
                                                                                                                        IntegerArgumentType.getInteger(context, "x1"),
                                                                                                                        IntegerArgumentType.getInteger(context, "y1"),
                                                                                                                        IntegerArgumentType.getInteger(context, "z1")
                                                                                                                ),
                                                                                                                new BlockPos(
                                                                                                                        IntegerArgumentType.getInteger(context, "x2"),
                                                                                                                        IntegerArgumentType.getInteger(context, "y2"),
                                                                                                                        IntegerArgumentType.getInteger(context, "z2")
                                                                                                                )
                                                                                                        )
                                                                                                )
                                                                                )
                                                                )
                                                )
                                )
                );
    }

    @FunctionalInterface
    private interface RangeCommandExecutor {

        int run(
                CommandContext<CommandSourceStack> context,
                BlockPos corner1,
                BlockPos corner2
        ) throws CommandSyntaxException;
    }

    // ------------------------------------------------------------
    // /deltachunk add
    // ------------------------------------------------------------

    private static int runAdd(
            CommandContext<CommandSourceStack> context,
            BlockPos corner1,
            BlockPos corner2
    ) throws CommandSyntaxException {

        CommandSourceStack source = context.getSource();

        ServerLevel level = source.getLevel();

        MinecraftServer server = source.getServer();

        WamStore store = DeltaChunk.getStore(server);

        if (store == null) {

            source.sendFailure(
                    Component.literal(
                            "[DeltaChunk] No active WAM store for this " +
                            "server (this shouldn't happen while a " +
                            "world is running)."
                    )
            );

            return 0;
        }

        BoundingBox box = BoundingBox.of(corner1, corner2);

        CommandSyntaxException tooLarge =
                box.rejectIfLargerThan(MAX_BLOCKS_PER_INVOCATION);

        if (tooLarge != null) {
            throw tooLarge;
        }

        String dimension = dimensionId(level);

        /*
         * Group by region up front, same as the automatic end-of-
         * session flush does, so each affected .wam file is only
         * opened/rewritten once even if the box spans many chunks.
         */
        Map<Long, Map<Long, BlockDelta>> byRegion = new HashMap<>();

        long blocksSnapshotted = 0;

        for (BlockPos pos : box) {

            BlockState state = level.getBlockState(pos);

            BlockEntity blockEntity = level.getBlockEntity(pos);

            CompoundTag blockEntityTag = null;

            if (blockEntity != null) {

                blockEntityTag =
                        blockEntity.saveWithFullMetadata(
                                level.registryAccess()
                        );
            }

            BlockDelta delta =
                    new BlockDelta(
                            BlockDelta.serializeState(state),
                            blockEntityTag
                    );

            long regionKey = regionKeyFor(pos);

            byRegion
                    .computeIfAbsent(
                            regionKey,
                            key -> new HashMap<>()
                    )
                    .put(pos.asLong(), delta);

            blocksSnapshotted++;
        }

        int regionsWritten =
                flushToRegions(
                        store,
                        dimension,
                        byRegion,
                        /* removing = */ false
                );

        if (regionsWritten < 0) {

            source.sendFailure(
                    Component.literal(
                            "[DeltaChunk] Failed to write WAM data for " +
                            "one or more regions; check server logs. " +
                            "Some positions in the box may not have " +
                            "been saved."
                    )
            );

            return 0;
        }

        long finalBlocksSnapshotted = blocksSnapshotted;

        source.sendSuccess(
                () -> Component.translatable("message.deltachunk.addSuccess",finalBlocksSnapshotted,regionsWritten),
                true
        );

        return (int) Math.min(blocksSnapshotted, Integer.MAX_VALUE);
    }

    // ------------------------------------------------------------
    // /deltachunk delete
    // ------------------------------------------------------------

    private static int runDelete(
            CommandContext<CommandSourceStack> context,
            BlockPos corner1,
            BlockPos corner2
    ) throws CommandSyntaxException {

        CommandSourceStack source = context.getSource();

        ServerLevel level = source.getLevel();

        MinecraftServer server = source.getServer();

        WamStore store = DeltaChunk.getStore(server);

        if (store == null) {

            source.sendFailure(
                    Component.literal(
                            "[DeltaChunk] No active WAM store for this " +
                            "server (this shouldn't happen while a " +
                            "world is running)."
                    )
            );

            return 0;
        }

        BoundingBox box = BoundingBox.of(corner1, corner2);

        CommandSyntaxException tooLarge =
                box.rejectIfLargerThan(MAX_BLOCKS_PER_INVOCATION);

        if (tooLarge != null) {
            throw tooLarge;
        }

        String dimension = dimensionId(level);

        Map<Long, Set<Long>> byRegion = new HashMap<>();

        long blocksMarkedForRemoval = 0;

        for (BlockPos pos : box) {

            long regionKey = regionKeyFor(pos);

            byRegion
                    .computeIfAbsent(
                            regionKey,
                            key -> new HashSet<>()
                    )
                    .add(pos.asLong());

            blocksMarkedForRemoval++;
        }

        int regionsWritten =
                removeFromRegions(
                        store,
                        dimension,
                        byRegion
                );

        if (regionsWritten < 0) {

            source.sendFailure(
                    Component.literal(
                            "[DeltaChunk] Failed to update WAM data for " +
                            "one or more regions; check server logs. " +
                            "Some positions in the box may not have " +
                            "been removed."
                    )
            );

            return 0;
        }

        long finalBlocksMarkedForRemoval = blocksMarkedForRemoval;

        source.sendSuccess(
                () -> Component.translatable("message.deltachunk.removeSuccess",finalBlocksMarkedForRemoval,regionsWritten),
                true
        );

        return (int) Math.min(blocksMarkedForRemoval, Integer.MAX_VALUE);
    }

    // ------------------------------------------------------------
    // Shared helpers
    // ------------------------------------------------------------

    private static int flushToRegions(
            WamStore store,
            String dimension,
            Map<Long, Map<Long, BlockDelta>> byRegion,
            boolean removing
    ) {

        int written = 0;

        for (Map.Entry<Long, Map<Long, BlockDelta>> entry : byRegion.entrySet()) {

            int regionX = unpackRegionX(entry.getKey());
            int regionZ = unpackRegionZ(entry.getKey());

            try {

                store.mergeRegion(
                        dimension,
                        regionX,
                        regionZ,
                        entry.getValue()
                );

                written++;

            } catch (IOException exception) {

                LOGGER.error(
                        "[DeltaChunk] /deltachunk add failed to write " +
                        "region {},{} for {}.",
                        regionX,
                        regionZ,
                        dimension,
                        exception
                );

                return -1;
            }
        }

        return written;
    }

    private static int removeFromRegions(
            WamStore store,
            String dimension,
            Map<Long, Set<Long>> byRegion
    ) {

        int written = 0;

        for (Map.Entry<Long, Set<Long>> entry : byRegion.entrySet()) {

            int regionX = unpackRegionX(entry.getKey());
            int regionZ = unpackRegionZ(entry.getKey());

            try {

                store.removeRegion(
                        dimension,
                        regionX,
                        regionZ,
                        entry.getValue()
                );

                written++;

            } catch (IOException exception) {

                LOGGER.error(
                        "[DeltaChunk] /deltachunk delete failed to " +
                        "update region {},{} for {}.",
                        regionX,
                        regionZ,
                        dimension,
                        exception
                );

                return -1;
            }
        }

        return written;
    }

    private static long regionKeyFor(BlockPos pos) {

        ChunkPos chunkPos = new ChunkPos(pos);

        return packRegionKey(
                chunkPos.getRegionX(),
                chunkPos.getRegionZ()
        );
    }

    private static long packRegionKey(int regionX, int regionZ) {

        return (((long) regionX) << 32)
                ^ (regionZ & 0xFFFFFFFFL);
    }

    private static int unpackRegionX(long key) {
        return (int) (key >> 32);
    }

    private static int unpackRegionZ(long key) {
        return (int) key;
    }

    private static String dimensionId(ServerLevel level) {

        return level.dimension().location().toString();
    }

    /**
     * Small inclusive-box iterator over every BlockPos between two
     * corners (in either order along each axis), separated out as
     * its own type mainly so the block-count cap can be checked
     * BEFORE iterating and writing anything, rather than discovering
     * "this box is too big" partway through a partially-applied
     * command.
     */
    private static final class BoundingBox
            implements Iterable<BlockPos> {

        private final int minX;
        private final int minY;
        private final int minZ;
        private final int maxX;
        private final int maxY;
        private final int maxZ;

        private BoundingBox(
                int minX, int minY, int minZ,
                int maxX, int maxY, int maxZ
        ) {

            this.minX = minX;
            this.minY = minY;
            this.minZ = minZ;
            this.maxX = maxX;
            this.maxY = maxY;
            this.maxZ = maxZ;
        }

        static BoundingBox of(BlockPos a, BlockPos b) {

            return new BoundingBox(
                    Math.min(a.getX(), b.getX()),
                    Math.min(a.getY(), b.getY()),
                    Math.min(a.getZ(), b.getZ()),
                    Math.max(a.getX(), b.getX()),
                    Math.max(a.getY(), b.getY()),
                    Math.max(a.getZ(), b.getZ())
            );
        }

        long blockCount() {

            long sizeX = (long) (maxX - minX) + 1;
            long sizeY = (long) (maxY - minY) + 1;
            long sizeZ = (long) (maxZ - minZ) + 1;

            return sizeX * sizeY * sizeZ;
        }

        /**
         * @return a CommandSyntaxException to throw if this box
         * exceeds {@code limit} blocks, or null if it's within
         * bounds. Returning rather than throwing directly keeps this
         * a plain value-returning check the caller can use with
         * "if not null, throw it", matching how command argument
         * validation elsewhere in vanilla surfaces size-limit errors
         * (e.g. /fill's own too-many-blocks check).
         */
        CommandSyntaxException rejectIfLargerThan(long limit) {

            long count = blockCount();

            if (count <= limit) {
                return null;
            }

            return new com.mojang.brigadier.exceptions.SimpleCommandExceptionType(
                    Component.literal(
                            "[DeltaChunk] Box too large: " + count +
                            " blocks requested, limit is " + limit +
                            ". Split this into smaller /deltachunk " +
                            "calls."
                    )
            ).create();
        }

        @Override
        public java.util.Iterator<BlockPos> iterator() {

            return new java.util.Iterator<>() {

                int x = minX;
                int y = minY;
                int z = minZ;
                boolean done = false;

                @Override
                public boolean hasNext() {
                    return !done;
                }

                @Override
                public BlockPos next() {

                    BlockPos result = new BlockPos(x, y, z);

                    x++;

                    if (x > maxX) {

                        x = minX;
                        y++;

                        if (y > maxY) {

                            y = minY;
                            z++;

                            if (z > maxZ) {
                                done = true;
                            }
                        }
                    }

                    return result;
                }
            };
        }
    }
}
